name: fitted_box_with_siblings
description: "A widget that scales a first child like FittedBox while positioning sibling widgets at computed rects."
version: 0.0.1
homepage: https://github.com/ronjb/fitted_box_with_siblings

environment:
  sdk: ^3.9.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints_plus: ^3.2.0
  flutter_test:
    sdk: flutter
